name: docs-deploy

on: # push 到 main 分支时触发部署
  push:
    branches: [main]

jobs:  # workflow 
  docs:
    runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境（必填）

    steps:
      - uses: actions/checkout@v2
        with:
          # with 字段用于指定动作的输入参数, 深度0表示要拉取所有提交记录的完整历史
          fetch-depth: 0

      # 该工作流程将使用 pnpm/action-setup 动作来安装 pnpm，并将其版本设置为 8。
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      # 运行构建脚本
      - name: Build vitepress site
        run: pnpm docs:build
        env:
          DOC_ENV: preview
          NODE_OPTIONS: --max-old-space-size=4096

      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          target_branch: gh-pages
          build_dir: packages/.vitepress/dist
